<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Serilog" Version="*" />
		<PackageReference Include="Serilog.Sinks.Console" Version="*" />
		<PackageReference Include="Serilog.Sinks.File" Version="*" />
		<PackageReference Include="Serilog.Sinks.Debug" Version="*" />
		<PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
		<PackageReference Include="Serilog.Sinks.Xunit2" Version="1.1.0" />
		<PackageReference Include="System.Reactive" Version="6.0.1" />
		<PackageReference Include="System.Reactive.Linq" Version="6.0.1" />
	</ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpPad.SqlCore\SharpPad.SqlCore.csproj" />
  </ItemGroup>

</Project>